### ISSUE TITLE
Forked, but up-to-date?

### ISSUE THREAD

**Issue by sanderlv** [ginkage/MHI-AC-Ctrl-ESPHome#34]
Hi,  I read:
MHI-AC-Ctrl-core.* files were forked directly, with no modification

Does this mean the original files from below are not needed to be updated?
https://github.com/absalom-muc/MHI-AC-Ctrl/tree/master/src

**Comment by jeroenkl** [comment]
@ginkage is it?

**Comment by ginkage** [comment]
Even with "normal" GitHub forks (which this project isn't, as it only uses a handful of files), the original files would have to be updated manually. At the moment, the files are slightly behind the original repo.
Unfortunately, due to the war in Ukraine, I don't have access to my AC unit, and won't be able to test anything for a while...

**Comment by ginkage** [comment]
I mean, try and see if it works (and create a pull request if it does), by all means. :)
